[package]
name = "paco-codegen-cranelift"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
autotests = false

[dependencies]
cranelift-codegen = { version = "0.135.2", features = ["x86", "arm64"] }
cranelift-frontend = "0.135.2"
cranelift-module = "0.135.2"
cranelift-native = "0.135.2"
cranelift-object = "0.135.2"
gimli = { version = "0.33.0", default-features = false, features = ["std", "write"] }
object = "0.40.0"
paco-diag.workspace = true
paco-mir.workspace = true
paco-span.workspace = true
paco-types.workspace = true
target-lexicon = "0.13"

[lib]
path = "src/lib.rs"

[dev-dependencies]
cranelift-jit = "0.135.2"
paco-borrow.workspace = true
paco-runtime-ffi = { path = "../../runtime/paco-runtime-ffi" }
paco-syntax.workspace = true

[[test]]
name = "main"
path = "tests/main.rs"
